"""
ROUGE Operations Manager and Platform Helper.

Centralizes all operations: working directory management, OS-aware commands,
virtual environment creation, and context sharing between agents.
"""

import json
import platform
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


class PlatformHelper:
    """Static utility for OS-aware command generation."""

    @staticmethod
    def get_os() -> str:
        """Get normalized OS name: 'windows', 'linux', or 'darwin'."""
        system = platform.system().lower()
        if system == "windows":
            return "windows"
        elif system == "darwin":
            return "darwin"
        else:
            return "linux"

    @staticmethod
    def is_windows() -> bool:
        return PlatformHelper.get_os() == "windows"

    @staticmethod
    def get_python_cmd() -> str:
        """Get the correct Python command for the current OS."""
        if PlatformHelper.is_windows():
            return "python"
        return "python3"

    @staticmethod
    def get_uv_run_cmd() -> List[str]:
        """Get the uv run command prefix."""
        return ["uv", "run"]

    @staticmethod
    def get_uv_pip_install_cmd() -> List[str]:
        """Get the uv pip install command."""
        return ["uv", "pip", "install"]

    @staticmethod
    def get_shell_info() -> Dict[str, str]:
        """Get shell information for the current OS."""
        if PlatformHelper.is_windows():
            return {"shell": "powershell", "ext": ".ps1", "comment": "#"}
        return {"shell": "bash", "ext": ".sh", "comment": "#"}

    @staticmethod
    def get_activate_cmd(venv_path: str) -> str:
        """Get the OS-aware venv activation command.

        Args:
            venv_path: Path to the virtual environment directory

        Returns:
            Shell command to activate the venv
        """
        venv = Path(venv_path)
        if PlatformHelper.is_windows():
            return str(venv / "Scripts" / "activate.ps1")
        return f"source {venv / 'bin' / 'activate'}"

    @staticmethod
    def get_venv_python(venv_path: str) -> str:
        """Get the path to the Python binary inside a venv.

        Args:
            venv_path: Path to the virtual environment directory

        Returns:
            Path to the venv's Python binary
        """
        venv = Path(venv_path)
        if PlatformHelper.is_windows():
            return str(venv / "Scripts" / "python.exe")
        return str(venv / "bin" / "python")

    @staticmethod
    def get_path_separator() -> str:
        """Get the OS-aware path separator."""
        if PlatformHelper.is_windows():
            return "\\"
        return "/"

    @staticmethod
    def get_os_summary() -> str:
        """Get a human-readable OS summary for LLM prompts."""
        os_name = PlatformHelper.get_os()
        shell = PlatformHelper.get_shell_info()
        return (
            f"Operating System: {os_name}\n"
            f"Shell: {shell['shell']}\n"
            f"Python Command: {PlatformHelper.get_python_cmd()}\n"
            f"Package Manager: uv (use 'uv pip install' or 'uvx')\n"
            f"Script Extension: {shell['ext']}"
        )


class RougeOperationsManager:
    """Manage the .rouge_operations working directory for all ROUGE operations.

    Creates and maintains the following structure:
        .rouge_operations/
        ├── deliverables/     # Agent output artifacts
        ├── venvs/            # Isolated virtual environments
        ├── context/          # Shared context store between agents
        └── logs/             # Operation logs
    """

    OPERATIONS_DIR = ".rouge_operations"

    def __init__(self, repo_path: str):
        """Initialize the operations manager.

        Args:
            repo_path: Path to the target repository
        """
        self.repo_path = Path(repo_path)
        self.ops_path = self.repo_path / self.OPERATIONS_DIR
        self._ensure_structure()

    def _ensure_structure(self):
        """Create the .rouge_operations directory structure."""
        subdirs = ["deliverables", "venvs", "context", "logs"]
        for subdir in subdirs:
            (self.ops_path / subdir).mkdir(parents=True, exist_ok=True)

        # Create .gitignore inside .rouge_operations
        gitignore = self.ops_path / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text("# Auto-generated by ROUGE — ignore all operations\n*\n")

    @property
    def deliverables_path(self) -> Path:
        """Get the deliverables directory path."""
        return self.ops_path / "deliverables"

    @property
    def venvs_path(self) -> Path:
        """Get the venvs directory path."""
        return self.ops_path / "venvs"

    @property
    def context_path(self) -> Path:
        """Get the context directory path."""
        return self.ops_path / "context"

    @property
    def logs_path(self) -> Path:
        """Get the logs directory path."""
        return self.ops_path / "logs"

    @property
    def context_file(self) -> Path:
        """Get the shared context JSON file path."""
        return self.context_path / "shared_context.json"

    # ============================================
    # Virtual Environment Management
    # ============================================

    def create_venv(self, name: str = "testing") -> Dict[str, Any]:
        """Create a virtual environment using uv.

        Args:
            name: Name of the venv (creates .rouge_operations/venvs/{name}/)

        Returns:
            Dict with success status and venv path
        """
        venv_path = self.venvs_path / name

        if venv_path.exists():
            return {
                "success": True,
                "venv_path": str(venv_path),
                "message": f"Venv '{name}' already exists",
                "python_path": PlatformHelper.get_venv_python(str(venv_path)),
            }

        try:
            result = subprocess.run(
                ["uv", "venv", str(venv_path)],
                capture_output=True,
                text=True,
                timeout=120,
                cwd=str(self.repo_path),
            )

            if result.returncode == 0:
                return {
                    "success": True,
                    "venv_path": str(venv_path),
                    "python_path": PlatformHelper.get_venv_python(str(venv_path)),
                    "activate_cmd": PlatformHelper.get_activate_cmd(str(venv_path)),
                    "message": f"Created venv '{name}' at {venv_path}",
                }
            else:
                return {
                    "success": False,
                    "error": f"uv venv failed: {result.stderr}",
                }

        except FileNotFoundError:
            return {
                "success": False,
                "error": "uv not found. Install from https://docs.astral.sh/uv/",
            }
        except subprocess.TimeoutExpired:
            return {"success": False, "error": "Venv creation timed out (120s)"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    def get_venv_python(self, name: str = "testing") -> Optional[str]:
        """Get the Python binary path for a specific venv.

        Args:
            name: Name of the venv

        Returns:
            Path to Python binary, or None if venv doesn't exist
        """
        venv_path = self.venvs_path / name
        if not venv_path.exists():
            return None
        return PlatformHelper.get_venv_python(str(venv_path))

    def install_in_venv(
        self, packages: List[str], name: str = "testing"
    ) -> Dict[str, Any]:
        """Install packages in a specific venv using uv.

        Args:
            packages: List of package names to install
            name: Name of the venv

        Returns:
            Dict with installation results
        """
        venv_path = self.venvs_path / name
        if not venv_path.exists():
            return {"success": False, "error": f"Venv '{name}' does not exist"}

        try:
            python_path = PlatformHelper.get_venv_python(str(venv_path))
            cmd = ["uv", "pip", "install", "--python", python_path] + packages

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300,
                cwd=str(self.repo_path),
            )

            return {
                "success": result.returncode == 0,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "packages": packages,
            }

        except Exception as e:
            return {"success": False, "error": str(e)}

    # ============================================
    # Context Management
    # ============================================

    def read_context(self) -> Dict[str, Any]:
        """Read the shared context store.

        Returns:
            The shared context dictionary
        """
        if not self.context_file.exists():
            return {
                "agents": {},
                "metadata": {
                    "created_at": datetime.now().isoformat(),
                    "last_updated": None,
                },
            }

        try:
            with open(self.context_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, Exception):
            return {"agents": {}, "metadata": {"error": "Failed to read context"}}

    def write_context(
        self, agent_name: str, data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Write agent data to the shared context store.

        Each agent's context is stored under its name key,
        so subsequent agents can read what prior agents discovered.

        Args:
            agent_name: Name of the agent writing context
            data: Context data to store

        Returns:
            Dict with success status
        """
        try:
            context = self.read_context()

            context["agents"][agent_name] = {
                "data": data,
                "timestamp": datetime.now().isoformat(),
            }
            context["metadata"]["last_updated"] = datetime.now().isoformat()

            with open(self.context_file, "w", encoding="utf-8") as f:
                json.dump(context, f, indent=2, default=str)

            return {"success": True, "agent": agent_name}

        except Exception as e:
            return {"success": False, "error": str(e)}

    def clear_context(self) -> Dict[str, Any]:
        """Clear the shared context store (for a fresh run).

        Returns:
            Dict with success status
        """
        try:
            if self.context_file.exists():
                self.context_file.unlink()
            return {"success": True, "message": "Context cleared"}
        except Exception as e:
            return {"success": False, "error": str(e)}

    # ============================================
    # Cleanup
    # ============================================

    def cleanup(self, keep_deliverables: bool = True):
        """Clean up the .rouge_operations directory.

        Args:
            keep_deliverables: If True, preserve the deliverables folder
        """
        if keep_deliverables:
            # Remove everything except deliverables
            for subdir in ["venvs", "context", "logs"]:
                path = self.ops_path / subdir
                if path.exists():
                    shutil.rmtree(path)
            self._ensure_structure()
        else:
            if self.ops_path.exists():
                shutil.rmtree(self.ops_path)
            self._ensure_structure()
