"""
Example API Test Suite Generated by ROUGE api-test-engineer agent
=================================================================

This demonstrates REST API testing with pytest and requests.
Includes: Authentication, CRUD operations, validation, performance
Generated by: api-test-engineer agent
"""

import pytest
import requests
from typing import Dict
import time


BASE_URL = "https://api.example.com/v1"


# ============================================================
# Fixtures (Generated by test-config-manager agent)
# ============================================================

@pytest.fixture(scope="session")
def auth_token() -> str:
    """Get authentication token for API requests"""
    response = requests.post(
        f"{BASE_URL}/auth/login",
        json={"username": "testuser", "password": "testpass"}
    )
    assert response.status_code == 200
    return response.json()["access_token"]


@pytest.fixture
def auth_headers(auth_token: str) -> Dict[str, str]:
    """Get authentication headers"""
    return {
        "Authorization": f"Bearer {auth_token}",
        "Content-Type": "application/json"
    }


@pytest.fixture
def test_user_data() -> Dict[str, str]:
    """Generate test user data"""
    from faker import Faker
    fake = Faker()
    return {
        "username": fake.user_name(),
        "email": fake.email(),
        "first_name": fake.first_name(),
        "last_name": fake.last_name(),
        "role": "user"
    }


# ============================================================
# User API Tests (Generated by api-test-engineer agent)
# ============================================================

@pytest.mark.api
@pytest.mark.smoke
class TestUserAPI:
    """Test suite for User API endpoints"""

    def test_get_users_list(self, auth_headers):
        """Verify GET /users returns paginated user list"""
        response = requests.get(
            f"{BASE_URL}/users",
            headers=auth_headers,
            params={"page": 1, "limit": 10}
        )

        assert response.status_code == 200
        data = response.json()

        assert "users" in data
        assert "total" in data
        assert "page" in data
        assert isinstance(data["users"], list)
        assert len(data["users"]) <= 10

    def test_create_user(self, auth_headers, test_user_data):
        """Verify POST /users creates new user"""
        response = requests.post(
            f"{BASE_URL}/users",
            headers=auth_headers,
            json=test_user_data
        )

        assert response.status_code == 201
        data = response.json()

        assert data["username"] == test_user_data["username"]
        assert data["email"] == test_user_data["email"]
        assert "id" in data
        assert "created_at" in data

        # Cleanup: Store user ID for deletion
        pytest.created_user_id = data["id"]

    def test_get_user_by_id(self, auth_headers):
        """Verify GET /users/{id} returns specific user"""
        if not hasattr(pytest, "created_user_id"):
            pytest.skip("No user created in previous test")

        response = requests.get(
            f"{BASE_URL}/users/{pytest.created_user_id}",
            headers=auth_headers
        )

        assert response.status_code == 200
        data = response.json()

        assert data["id"] == pytest.created_user_id
        assert "username" in data
        assert "email" in data

    def test_update_user(self, auth_headers):
        """Verify PATCH /users/{id} updates user"""
        if not hasattr(pytest, "created_user_id"):
            pytest.skip("No user created in previous test")

        update_data = {"first_name": "Updated"}

        response = requests.patch(
            f"{BASE_URL}/users/{pytest.created_user_id}",
            headers=auth_headers,
            json=update_data
        )

        assert response.status_code == 200
        data = response.json()

        assert data["first_name"] == "Updated"

    def test_delete_user(self, auth_headers):
        """Verify DELETE /users/{id} removes user"""
        if not hasattr(pytest, "created_user_id"):
            pytest.skip("No user created in previous test")

        response = requests.delete(
            f"{BASE_URL}/users/{pytest.created_user_id}",
            headers=auth_headers
        )

        assert response.status_code == 204

        # Verify deletion
        get_response = requests.get(
            f"{BASE_URL}/users/{pytest.created_user_id}",
            headers=auth_headers
        )
        assert get_response.status_code == 404


# ============================================================
# Validation Tests (Generated by api-test-engineer agent)
# ============================================================

@pytest.mark.api
@pytest.mark.validation
class TestAPIValidation:
    """Test API input validation and error handling"""

    @pytest.mark.parametrize("invalid_data,expected_error", [
        ({"username": "ab"}, "Username must be at least 3 characters"),
        ({"username": "validuser"}, "Email is required"),
        ({"username": "validuser", "email": "invalid"}, "Invalid email format"),
        ({"username": "user", "email": "user@test.com", "role": "superadmin"}, "Invalid role"),
    ])
    def test_create_user_validation(self, auth_headers, invalid_data, expected_error):
        """Test user creation validation errors"""
        response = requests.post(
            f"{BASE_URL}/users",
            headers=auth_headers,
            json=invalid_data
        )

        assert response.status_code == 400
        data = response.json()

        assert "error" in data
        assert expected_error in data["error"]["message"]

    def test_unauthorized_access(self):
        """Verify API requires authentication"""
        response = requests.get(f"{BASE_URL}/users")

        assert response.status_code == 401
        assert "error" in response.json()

    def test_invalid_token(self):
        """Verify invalid token is rejected"""
        headers = {"Authorization": "Bearer invalid_token"}

        response = requests.get(
            f"{BASE_URL}/users",
            headers=headers
        )

        assert response.status_code == 401

    def test_user_not_found(self, auth_headers):
        """Verify 404 for non-existent user"""
        response = requests.get(
            f"{BASE_URL}/users/99999",
            headers=auth_headers
        )

        assert response.status_code == 404
        data = response.json()

        assert "error" in data
        assert "not found" in data["error"]["message"].lower()


# ============================================================
# Performance Tests (Generated by performance-tester agent)
# ============================================================

@pytest.mark.api
@pytest.mark.performance
class TestAPIPerformance:
    """Test API response time and throughput"""

    def test_api_response_time(self, auth_headers):
        """Verify API responds within acceptable time"""
        start = time.time()
        response = requests.get(
            f"{BASE_URL}/users",
            headers=auth_headers
        )
        duration = time.time() - start

        assert response.status_code == 200
        assert duration < 1.0, f"API took {duration:.2f}s (expected < 1s)"

    def test_concurrent_requests(self, auth_headers):
        """Test API handles concurrent requests"""
        import concurrent.futures

        def make_request():
            return requests.get(
                f"{BASE_URL}/users",
                headers=auth_headers
            )

        with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
            futures = [executor.submit(make_request) for _ in range(10)]
            results = [f.result() for f in concurrent.futures.as_completed(futures)]

        # All requests should succeed
        assert all(r.status_code == 200 for r in results)


# ============================================================
# Contract Tests (Generated by contract-tester agent)
# ============================================================

@pytest.mark.api
@pytest.mark.contract
class TestAPIContract:
    """Test API adheres to expected contract/schema"""

    def test_user_schema(self, auth_headers):
        """Verify user object matches expected schema"""
        response = requests.get(
            f"{BASE_URL}/users",
            headers=auth_headers
        )

        assert response.status_code == 200
        users = response.json()["users"]

        if users:
            user = users[0]
            required_fields = ["id", "username", "email", "created_at"]

            for field in required_fields:
                assert field in user, f"Missing required field: {field}"

            # Type validation
            assert isinstance(user["id"], int)
            assert isinstance(user["username"], str)
            assert isinstance(user["email"], str)

    def test_pagination_schema(self, auth_headers):
        """Verify pagination response structure"""
        response = requests.get(
            f"{BASE_URL}/users?page=1&limit=5",
            headers=auth_headers
        )

        assert response.status_code == 200
        data = response.json()

        required_fields = ["users", "total", "page", "limit", "pages"]

        for field in required_fields:
            assert field in data, f"Missing pagination field: {field}"

        assert isinstance(data["users"], list)
        assert isinstance(data["total"], int)
        assert data["page"] == 1
        assert data["limit"] == 5


# ============================================================
# Running the tests:
# ==================
#
# Run all API tests:
#   pytest tests/ -m api
#
# Run specific test class:
#   pytest tests/test_api.py::TestUserAPI -v
#
# Run with specific markers:
#   pytest -m "api and smoke"
#   pytest -m "api and not performance"
#
# Generate detailed report:
#   pytest --tb=short --html=report.html
#
# Parallel execution:
#   pytest -n auto -m api
# ============================================================
