"""
Example Test Suite Generated by ROUGE TestAutomationWorkflow
============================================================

This demonstrates the output of the ui-test-scripter agent using Playwright.
Framework: Playwright with Page Object Model
Test Data: Factory pattern with Faker
CI Integration: GitHub Actions ready
"""

import pytest
from playwright.sync_api import Page, expect
from faker import Faker

fake = Faker()


# ============================================================
# Page Objects (Generated by framework-builder agent)
# ============================================================

class LoginPage:
    """Page Object for login functionality"""

    def __init__(self, page: Page):
        self.page = page
        self.username_input = page.locator("#username")
        self.password_input = page.locator("#password")
        self.login_button = page.locator("button[type='submit']")
        self.error_message = page.locator(".error-message")

    def navigate(self):
        self.page.goto("https://demo.example.com/login")

    def login(self, username: str, password: str):
        self.username_input.fill(username)
        self.password_input.fill(password)
        self.login_button.click()


class DashboardPage:
    """Page Object for dashboard"""

    def __init__(self, page: Page):
        self.page = page
        self.welcome_message = page.locator(".welcome-user")
        self.logout_button = page.locator("#logout")

    def is_loaded(self) -> bool:
        return self.welcome_message.is_visible()


# ============================================================
# Test Data Factories (Generated by test-data-factory agent)
# ============================================================

class UserFactory:
    """Generate test user data"""

    @staticmethod
    def create_valid_user():
        return {
            "username": fake.user_name(),
            "email": fake.email(),
            "password": "ValidP@ssw0rd123",
            "first_name": fake.first_name(),
            "last_name": fake.last_name()
        }


# ============================================================
# Test Configuration (Generated by test-config-manager agent)
# ============================================================

@pytest.fixture(scope="session")
def base_url(request):
    """Multi-environment configuration"""
    env = request.config.getoption("--env", default="staging")
    urls = {
        "dev": "https://dev.example.com",
        "staging": "https://staging.example.com",
        "production": "https://example.com"
    }
    return urls.get(env, urls["staging"])


# ============================================================
# UI Tests (Generated by ui-test-scripter agent)
# ============================================================

@pytest.mark.ui
@pytest.mark.smoke
class TestLoginFlow:
    """Test suite for login functionality"""

    def test_successful_login(self, page: Page):
        """Verify user can login with valid credentials"""
        # Arrange
        user = UserFactory.create_valid_user()
        login_page = LoginPage(page)
        dashboard = DashboardPage(page)

        # Act
        login_page.navigate()
        login_page.login(user["username"], user["password"])

        # Assert
        expect(dashboard.welcome_message).to_be_visible()

    def test_invalid_credentials(self, page: Page):
        """Verify error message on invalid login"""
        login_page = LoginPage(page)
        login_page.navigate()
        login_page.login("invalid_user", "wrong_password")

        expect(login_page.error_message).to_contain_text("Invalid credentials")

    @pytest.mark.parametrize("username,password,expected_error", [
        ("", "password", "Username is required"),
        ("user", "", "Password is required"),
        ("ab", "pass", "Username must be at least 3 characters"),
    ])
    def test_validation_errors(self, page: Page, username: str, password: str, expected_error: str):
        """Test form validation messages"""
        login_page = LoginPage(page)
        login_page.navigate()
        login_page.login(username, password)

        expect(login_page.error_message).to_contain_text(expected_error)


@pytest.mark.ui
@pytest.mark.regression
class TestDashboard:
    """Dashboard functionality tests"""

    def test_dashboard_loads(self, page: Page):
        """Verify dashboard loads after login"""
        # Pre-condition: User is logged in
        dashboard = DashboardPage(page)
        assert dashboard.is_loaded()


# ============================================================
# Performance Tests (Generated by performance-tester agent)
# ============================================================

@pytest.mark.performance
def test_page_load_time(self, page: Page, base_url: str):
    """Verify page loads within acceptable time"""
    import time

    start = time.time()
    page.goto(f"{base_url}/login")
    page.wait_for_load_state("networkidle")
    duration = time.time() - start

    assert duration < 2.0, f"Page load took {duration}s (expected < 2s)"


# ============================================================
# Running the tests:
# ==================
#
# Run all tests:
#   pytest tests/
#
# Run specific markers:
#   pytest -m smoke
#   pytest -m regression
#
# Run with specific environment:
#   pytest --env=staging
#
# Parallel execution:
#   pytest -n auto
#
# Generate HTML report:
#   pytest --html=report.html
# ============================================================
