/**
 * SyntheticDataGenerator — Phase 2: GDPR-Compliant Test Data
 *
 * Generates realistic but non-PII data for integration and E2E tests.
 * Compliant with GDPR Article 32 (Security of processing).
 *
 * Produces deterministic (seeded) data for reproducible tests.
 */

// ---------- Types ----------

export interface SyntheticProfile {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
  address: SyntheticAddress
  dateOfBirth: string
  creditCard: SyntheticCreditCard
}

export interface SyntheticAddress {
  street: string
  city: string
  state: string
  zip: string
  country: string
}

export interface SyntheticCreditCard {
  number: string
  expiry: string
  cvv: string
  brand: string
}

export interface SyntheticDataSet {
  profiles: SyntheticProfile[]
  metadata: {
    count: number
    seed: number
    generatedAt: string
    gdprCompliant: true
  }
}

// ---------- Seed-based RNG ----------

class SeededRandom {
  private state: number

  constructor(seed: number) {
    this.state = seed
  }

  next(): number {
    this.state = (this.state * 1664525 + 1013904223) & 0xFFFFFFFF
    return (this.state >>> 0) / 0xFFFFFFFF
  }

  int(min: number, max: number): number {
    return Math.floor(this.next() * (max - min + 1)) + min
  }

  pick<T>(arr: readonly T[]): T {
    return arr[this.int(0, arr.length - 1)]!
  }
}

// ---------- Data pools ----------

const FIRST_NAMES = [
  'Aria', 'Kai', 'Luna', 'Zephyr', 'Nova', 'Orion', 'Sage', 'Phoenix',
  'River', 'Ember', 'Atlas', 'Jade', 'Rowan', 'Iris', 'Cypress', 'Wren',
  'Cedar', 'Hazel', 'Jasper', 'Coral', 'Aspen', 'Onyx', 'Raven', 'Sky',
] as const

const LAST_NAMES = [
  'Starling', 'Winterbourne', 'Ashford', 'Thornton', 'Blackwell', 'Stormrider',
  'Nightingale', 'Ironwood', 'Silverstone', 'Ravenscroft', 'Fairweather', 'Foxglove',
  'Hartwell', 'Mooreland', 'Oaksworth', 'Driftwood', 'Clearwater', 'Stonegate',
] as const

const CITIES = [
  'Testville', 'Mockton', 'Stubsburg', 'Fakerton', 'Synthdale', 'Dataport',
  'Fixturia', 'Assertown', 'Specville', 'Mockfield', 'Seedhaven', 'Genwood',
] as const

const STATES = ['TS', 'MK', 'SB', 'FK', 'SD', 'DP', 'FX', 'AT', 'SV', 'GN'] as const

const STREETS = [
  'Test Lane', 'Mock Avenue', 'Assert Boulevard', 'Fixture Street',
  'Synthetic Road', 'Sample Drive', 'Data Way', 'Seed Court',
] as const

const COUNTRIES = ['Testland'] as const

const CC_BRANDS = ['TestVisa', 'MockCard', 'SynthAX', 'FakeDiscover'] as const

// ---------- Generator ----------

export class SyntheticDataGenerator {
  private rng: SeededRandom

  constructor(seed = 42) {
    this.rng = new SeededRandom(seed)
  }

  /**
   * Generate a dataset of synthetic profiles.
   */
  generate(count: number, seed?: number): SyntheticDataSet {
    if (seed !== undefined) this.rng = new SeededRandom(seed)
    const profiles: SyntheticProfile[] = []
    for (let i = 0; i < count; i++) {
      profiles.push(this.generateProfile(i))
    }
    return {
      profiles,
      metadata: {
        count,
        seed: seed ?? 42,
        generatedAt: new Date().toISOString(),
        gdprCompliant: true,
      },
    }
  }

  /**
   * Generate a single synthetic profile.
   */
  generateProfile(index: number): SyntheticProfile {
    const firstName = this.rng.pick(FIRST_NAMES)
    const lastName = this.rng.pick(LAST_NAMES)
    const domain = 'test.niro.invalid'

    return {
      id: `synth-${String(index).padStart(6, '0')}`,
      firstName,
      lastName,
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@${domain}`,
      phone: `+1-555-${String(this.rng.int(100, 999))}-${String(this.rng.int(1000, 9999))}`,
      address: this.generateAddress(),
      dateOfBirth: this.generateDate(1960, 2005),
      creditCard: this.generateCreditCard(),
    }
  }

  /**
   * Generate test-safe SQL INSERT statements for profiles.
   */
  toSQL(profiles: SyntheticProfile[], tableName = 'users'): string {
    const lines = [`-- Synthetic test data generated by NiRo.ai (GDPR-compliant)`, '']
    for (const p of profiles) {
      const values = [
        `'${p.id}'`, `'${p.firstName}'`, `'${p.lastName}'`, `'${p.email}'`,
        `'${p.phone}'`, `'${p.address.city}'`, `'${p.address.country}'`,
      ].join(', ')
      lines.push(`INSERT INTO ${tableName} (id, first_name, last_name, email, phone, city, country) VALUES (${values});`)
    }
    lines.push('')
    return lines.join('\n')
  }

  /**
   * Generate test-safe JSON fixture.
   */
  toJSON(profiles: SyntheticProfile[]): string {
    return JSON.stringify(profiles, null, 2)
  }

  // --- Private generators ---

  private generateAddress(): SyntheticAddress {
    return {
      street: `${this.rng.int(1, 9999)} ${this.rng.pick(STREETS)}`,
      city: this.rng.pick(CITIES),
      state: this.rng.pick(STATES),
      zip: String(this.rng.int(10000, 99999)),
      country: this.rng.pick(COUNTRIES),
    }
  }

  private generateDate(minYear: number, maxYear: number): string {
    const year = this.rng.int(minYear, maxYear)
    const month = String(this.rng.int(1, 12)).padStart(2, '0')
    const day = String(this.rng.int(1, 28)).padStart(2, '0')
    return `${year}-${month}-${day}`
  }

  private generateCreditCard(): SyntheticCreditCard {
    // Generate obviously fake card numbers (all start with 0000)
    const num = `0000-${this.rng.int(1000, 9999)}-${this.rng.int(1000, 9999)}-${this.rng.int(1000, 9999)}`
    const expMonth = String(this.rng.int(1, 12)).padStart(2, '0')
    const expYear = this.rng.int(2026, 2035)
    return {
      number: num,
      expiry: `${expMonth}/${expYear}`,
      cvv: String(this.rng.int(100, 999)),
      brand: this.rng.pick(CC_BRANDS),
    }
  }
}
